ALTER TABLE business_profiles
    ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS country_code VARCHAR(20) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS email VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS contact_hours VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE business_leader_profiles
    ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS country_code VARCHAR(20) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS email VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS contact_hours VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE politician_profiles
    ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS country_code VARCHAR(20) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS email VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS contact_hours VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE celebrity_profiles
    ADD COLUMN IF NOT EXISTS mobile_number VARCHAR(50) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS country_code VARCHAR(20) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS email VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS contact_hours VARCHAR(255) NOT NULL DEFAULT '';

